apiVersion: v1
kind: BuildConfig
metadata:
  name: razeone.open-liberty-example
  labels:
    app: open-liberty-example
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: https://github.com/razeone/open-liberty-example
      ref: main
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: liberty
        - name: BRANCH
          value: main
